# Generated by Django 5.1.6 on 2025-02-16 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=40)),
                ('mapUrl', models.URLField()),
                ('ticket', models.URLField()),
                ('date', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('visited', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('duration', models.PositiveBigIntegerField()),
                ('company', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='VisitedAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualCost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('images', models.DateField()),
                ('moment', models.TextField()),
                ('attractionTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.attraction')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.AddField(
            model_name='rating',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.visitedattraction'),
        ),
    ]
