# Generated by Django 5.1.6 on 2025-02-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ammount',
            new_name='amount',
        ),
    ]
