# Generated by Django 5.1.6 on 2025-02-23 12:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_ammount_item_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=255)),
                ('position', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='company',
            new_name='trip_members',
        ),
        migrations.RenameField(
            model_name='visitedattraction',
            old_name='attractionTitle',
            new_name='attraction_id',
        ),
        migrations.RemoveField(
            model_name='visitedattraction',
            name='description',
        ),
        migrations.AddField(
            model_name='attraction',
            name='price',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='is_public',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitedattraction',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='visitedattraction',
            name='reviewed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitedattraction',
            name='images',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='column',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trip'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='column_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.column'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
