# Generated by Django 5.1.6 on 2025-03-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['position']},
        ),
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('trip_id', 'position')},
        ),
        migrations.RemoveField(
            model_name='trip',
            name='duration',
        ),
        migrations.AddField(
            model_name='column',
            name='title',
            field=models.CharField(default='Day', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Eleni', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attraction',
            name='category',
            field=models.CharField(choices=[('museum', 'Museum'), ('landmark', 'Landmark'), ('park', 'Park'), ('palace', 'Palace'), ('restaurant', 'Restaurant'), ('gallery', 'Gallery'), ('church', 'Church'), ('other', 'Other')], default='other', max_length=40),
        ),
        migrations.AlterField(
            model_name='visitedattraction',
            name='images',
            field=models.FileField(blank=True, help_text='Upload images from your visit', null=True, upload_to='visited_attractions/'),
        ),
        migrations.RemoveField(
            model_name='column',
            name='day',
        ),
    ]
