# Generated by Django 5.1.7 on 2025-03-31 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_column_options_alter_column_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='price',
        ),
    ]
