# Generated by Django 5.1.7 on 2025-03-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_attraction_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='mapUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='ticket',
            field=models.URLField(blank=True),
        ),
    ]
