# Generated by Django 5.1.6 on 2025-08-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_attraction_mapurl_alter_attraction_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
