# Generated by Django 5.1.6 on 2025-08-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
