# Generated by Django 5.1.6 on 2025-08-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_member_trip_end_time_trip_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='is_public',
        ),
    ]
