# Generated by Django 5.1.6 on 2025-08-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_trip_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip_members',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_members',
            field=models.JSONField(default=list),
        ),
    ]
