# Generated by Django 5.1.7 on 2026-01-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attraction',
            options={'ordering': ['column_id', 'position']},
        ),
        migrations.AddField(
            model_name='attraction',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
