# Generated by Django 5.1.7 on 2026-01-29 23:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_trip_check_start_date_before_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip_members',
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_members',
            field=models.ManyToManyField(blank=True, related_name='shared_trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
