# Generated by Django 5.1.7 on 2026-01-30 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_trip_trip_members_trip_trip_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='date',
        ),
    ]
