# Generated by Django 5.1.7 on 2026-01-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_attraction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='mapUrl',
            field=models.URLField(blank=True),
        ),
    ]
