# Generated by Django 5.1.7 on 2026-01-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_attraction_mapurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip_members',
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_members',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
